In [1]:
import pandas as pd

In [3]:
# Loading data from csv file

df = pd.read_csv('Source.csv')

In [4]:
df.shape[0]

438946

In [4]:
#top 5 tecords of DF
df.head(5)

,id,status,release_date,revenue,runtime,adult,budget,homepage,original_title,overview,poster_path,genres,production_companies,production_countries,spoken_languages,keywords,directors,writers,averageRating,cast
0,2,Released,21/10/1988,0,73,False,0,NaN,Ariel,After the coal mine he works at closes and his...,/ojDg0PGvs6R9xYFodRct2kdI6wC.jpg,"Drama, Comedy, Romance",Villealfa Filmproductions,Finland,Finnish,"prison, underdog, helsinki, finland, factory w...",Aki Kaurismäki,Aki Kaurismäki,7.4,"Turo Pajala, Susanna Haavisto, Matti Pellonpää..."
1,3,Released,17/10/1986,0,74,False,0,NaN,Varjoja paratiisissa,"Nikander, a rubbish collector and would-be ent...",/nj01hspawPof0mJmlgfjuLyJuRN.jpg,"Drama, Comedy, Romance",Villealfa Filmproductions,Finland,"English, Finnish, Swedish","helsinki, finland, salesclerk, garbage",Aki Kaurismäki,Aki Kaurismäki,7.4,"Matti Pellonpää, Kati Outinen, Sakari Kuosmane..."
2,5,Released,09/12/1995,4257354,98,False,4000000,https://www.miramax.com/movie/four-rooms/,Four Rooms,It's Ted the Bellhop's first night on the job....,/75aHn1NOYXh4M7L5shoeQ6NGykP.jpg,Comedy,"Miramax, A Band Apart",United States of America,English,"hotel, new year's eve, witch, bet, sperm, hote...","Allison Anders, Alexandre Rockwell, Robert Rod...","Allison Anders, Alexandre Rockwell, Robert Rod...",6.7,"Tim Roth, Jennifer Beals, Antonio Banderas, Va..."
3,6,Released,15/10/1993,12136938,109,False,21000000,NaN,Judgment Night,"While racing to a boxing match, Frank, Mike, J...",/3rvvpS9YPM5HB2f4HYiNiJVtdam.jpg,"Action, Crime, Thriller","Largo Entertainment, JVC",United States of America,English,"drug dealer, chicago, illinois, escape, one ni...",Stephen Hopkins,"Lewis Colick, Jere Cunningham",6.6,"Emilio Estevez, Cuba Gooding Jr., Denis Leary,..."
4,8,Released,01/01/2006,0,80,False,42000,http://lifeinloops.com,Life in Loops (A Megacities RMX),Timo Novotny labels his new project an experim...,/x7Sz339F2oC8mBf0DHCQpKizXaL.jpg,Documentary,inLoops,Austria,"English, Hindi, Japanese, Russian, Spanish",megacities,Timo Novotny,"Michael Glawogger, Timo Novotny",8.1,NaN

In [5]:
#Dropping records where id and title is redundant
df = df.drop_duplicates(subset=['id'], keep='first')
df = df.drop_duplicates(subset=['original_title'], keep='first')

In [7]:
df.shape[0]

388536

Creating & storing Fact table

In [6]:
#Creating & storing movie table
movie_cols = ['movie_id', 'original_title', 'averageRating', 'status', 'release_date', 'revenue', 'runtime', 'adult', 'budget', 'overview', 'poster_path']
df.rename(columns={'id': 'movie_id'}, inplace=True)
df_movie = df[movie_cols]
df_movie.to_csv('Dataset/Tables/movie.csv', index=False)

Creating & storing dimension table

In [70]:
#Creating & storing genre table with unique genre values and assigning genre_id
df_genres = df['genres'].str.split(',').explode().to_frame(name='genre')
df_genres['genre'] = df_genres['genre'].str.strip()
df_genres['_genres'] = df_genres['genre'].str.title()
df_genres = df_genres.drop_duplicates(subset = '_genres', keep='first').reset_index(drop=True)
df_genres = df_genres.drop(columns = '_genres')
df_genres['genre_id'] = df_genres.index + 1
df_genres.to_csv('Dataset/Tables/genre.csv', index=False)

In [71]:
#Creating & storing production_companies table with unique company names and assigning company_id
df_companies = df['production_companies'].str.split(',').explode().to_frame(name='production_company')
df_companies['production_company'] = df_companies['production_company'].str.strip()
df_companies['_production_companies'] = df_companies['production_company'].str.title()
df_companies = df_companies.drop_duplicates(subset = '_production_companies', keep='first').reset_index(drop=True)
df_companies = df_companies.drop(columns = '_production_companies')
df_companies['company_id'] = df_companies.index + 1
df_companies.to_csv('Dataset/Tables/company.csv', index=False)

In [72]:
#Creating & storing languages table with unique language names and assigning language_id
df_languages = df['spoken_languages'].str.strip().str.split(',').explode().to_frame(name='language')
df_languages['language'] = df_languages['language'].str.strip()
df_languages['_languages'] = df_languages['language'].str.title()
df_languages = df_languages.drop_duplicates(subset = '_languages', keep='first').reset_index(drop=True)
df_languages = df_languages.drop(columns = '_languages')
df_languages['language_id'] = df_languages.index + 1
df_languages.to_csv('Dataset/Tables/language.csv', index=False)

In [73]:
#Creating & storing director table with unique directors names and assigning director_id
df_directors = df['directors'].str.split(',').explode().to_frame(name='director')
df_directors['director'] = df_directors['director'].str.strip()
df_directors['_directors'] = df_directors['director'].str.strip().str.title()
df_directors = df_directors.drop_duplicates(subset = '_directors', keep='first').reset_index(drop=True)
df_directors = df_directors.drop(columns = '_directors')
df_directors['director_id'] = df_directors.index + 1
df_directors.to_csv('Dataset/Tables/director.csv', index=False)

In [74]:
#Creating & storing writer table with unique writers names and assigning writer_id
df_writers = df['writers'].str.split(',').explode().to_frame(name='writer')
df_writers['writer'] = df_writers['writer'].str.strip()
df_writers['_writers'] = df_writers['writer'].str.title()
df_writers = df_writers.drop_duplicates(subset = '_writers', keep='first').reset_index(drop=True)
df_writers = df_writers.drop(columns = '_writers')
df_writers['writer_id'] = df_writers.index + 1
df_writers.to_csv('Dataset/Tables/writer.csv', index=False)

In [75]:
#Creating & storing cast table with unique casts name and assigning cast_id
df_casts = df['cast'].str.split(',').explode().to_frame(name='cast')
df_casts['cast'] = df_casts['cast'].str.strip()
df_casts['_casts'] = df_casts['cast'].str.title()
df_casts = df_casts.drop_duplicates(subset = '_casts', keep='first').reset_index(drop=True)
df_casts = df_casts.drop(columns = '_casts')
df_casts['cast_id'] = df_casts.index + 1
df_casts.to_csv('Dataset/Tables/cast.csv', index=False)

Creating & storing relationship tables

In [81]:
#Creating & storing movie & genre relationship table
df_movie_genre = df[['movie_id','genres']].copy()
df_movie_genre['genres'] = df['genres'].str.split(',')
df_movie_genre = df_movie_genre.explode('genres').reset_index(drop=True)
df_movie_genre['genres'] = df_movie_genre['genres'].str.strip()
df_movie_genre = pd.merge(df_movie_genre, df_genres, how='left', left_on='genres', right_on='genre').drop(['genres','genre'],axis='columns').reset_index(drop=True)
df_movie_genre.to_csv('Dataset/Relationship_tables/movie_genre.csv', index=False)

In [82]:
#Creating & storing movie & production company relationship table
df_movie_company = df[['movie_id','production_companies']].copy()
df_movie_company['production_companies'] = df['production_companies'].str.split(',')
df_movie_company = df_movie_company.explode('production_companies').reset_index(drop=True)
df_movie_company['production_companies'] = df_movie_company['production_companies'].str.strip()
df_movie_company = pd.merge(df_movie_company, df_companies, how='left', left_on='production_companies', right_on='production_company').drop(['production_companies','production_company'],axis='columns').reset_index(drop=True)
df_movie_company.to_csv('Dataset/Relationship_tables/movie_company.csv', index=False)

In [83]:
#Creating & storing movie & production company relationship table
df_movie_company = df[['movie_id','production_companies']].copy()
df_movie_company['production_companies'] = df['production_companies'].str.split(',')
df_movie_company = df_movie_company.explode('production_companies').reset_index(drop=True)
df_movie_company['production_companies'] = df_movie_company['production_companies'].str.strip()

In [92]:
df_companies.head(10)

          production_company  company_id
0  Villealfa Filmproductions           1
1                    Miramax           2
2               A Band Apart           3
3        Largo Entertainment           4
4                        JVC           5
5                    inLoops           6
6                        NaN           7
7             Lucasfilm Ltd.           8
8           20th Century Fox           9
9                      Pixar          10

In [99]:
df_movie_company[df_movie_company['movie_id'] == 7270]['production_companies'].values

array(['Saturn Films', 'Scott Free Productions', 'Rickshaw Productions',
       'LivePlanet', 'ImageMovers', 'Warner Bros. Pictures',
       'HorsePower Entertainment'], dtype=object)

In [100]:
df_companies.head(5)

          production_company  company_id
0  Villealfa Filmproductions           1
1                    Miramax           2
2               A Band Apart           3
3        Largo Entertainment           4
4                        JVC           5

In [106]:
df_companies[df_companies['production_company']=='LivePlanet']

Empty DataFrame
Columns: [production_company, company_id]
Index: []

In [98]:
df[df['movie_id'] == 7270]['production_companies'].values

array(['Saturn Films, Scott Free Productions, Rickshaw Productions, LivePlanet, ImageMovers, Warner Bros. Pictures, HorsePower Entertainment'],
      dtype=object)

In [85]:
result = pd.merge(df_movie_company, df_companies, how='left', left_on='production_companies', right_on='production_company')

In [95]:
# result['company_id'] = result['company_id'].astype('int')
result[result['company_id'].isnull()].head(5)

       movie_id production_companies production_company  company_id
9101       7270           LivePlanet                NaN         NaN
9812       8273           LivePlanet                NaN         NaN
11437      9341           LivePlanet                NaN         NaN
13311     10070           LivePlanet                NaN         NaN
14166     10425    Eclectic pictures                NaN         NaN

In [ ]:
#Creating & storing movie & language relationship table
df_movie_language = df[['movie_id','spoken_languages']].copy()
df_movie_language['spoken_languages'] = df['spoken_languages'].str.split(',')
df_movie_language = df_movie_language.explode('spoken_languages').reset_index(drop=True)
df_movie_language.to_csv('Dataset/Relationship_tables/movie_language.csv', index=False)

In [ ]:
#Creating & storing movie & directors relationship table
df_movie_director = df[['movie_id','directors']].copy()
df_movie_director['directors'] = df['directors'].str.split(',')
df_movie_director = df_movie_director.explode('directors').reset_index(drop=True)
df_movie_director.to_csv('Dataset/Relationship_tables/movie_director.csv', index=False)

In [ ]:
#Creating & storing movie & writers relationship table
df_movie_writer = df[['movie_id','writers']].copy()
df_movie_writer['writers'] = df['writers'].str.split(',')
df_movie_writer = df_movie_writer.explode('writers').reset_index(drop=True)
df_movie_writer.to_csv('Dataset/Relationship_tables/movie_writer.csv', index=False)

In [ ]:
#Creating & storing movie & cast relationship table
df_movie_cast = df[['movie_id','cast']].copy()
df_movie_cast['cast'] = df['cast'].str.split(',')
df_movie_cast = df_movie_cast.explode('cast').reset_index(drop=True)
df_movie_cast.to_csv('Dataset/Relationship_tables/movie_cast.csv', index=False)